plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cloudwubi.glasskeyboard'
    compileSdk 33

    defaultConfig {
        applicationId "com.cloudwubi.glasskeyboard"
        minSdk 24
        targetSdk 33
        versionCode 13
        versionName "2.2-lite"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
